server:
    port: 13003
#spring.aop.auto: true
spring:
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/springboot_hibernate_demo?characterEncoding=UTF-8&useSSL=false&createDatabaseIfNotExist=true
        username: root
        password: ENC(JihOtyGINdIAdrUwTl68cQ==)
        tomcat:
            test-on-borrow: true
            validation-query: SELECT 1
            max-active: 50
            max-idle: 20
            min-idle: 15
            initial-size: 1
    jpa:
        hibernate: 
            ddl-auto: none
            dialect: org.hibernate.dialect.MySQLDialect
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
            format_sql: true
    application:
      name: Spring Boot Admin Web
#    boot:
#      admin:
#        url: http://localhost:${server.port}
    jackson:
      serialization:
        indent_output: true

liquibase:
    changeLog: "classpath:db/changelog/master.xml"


endpoints:
  health:
    sensitive: false

                
